// internal
import { Provider } from "./provider";
import "./globals.css";
// external

export const metadata = {
  title: "Next.js trading analytics",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
