// external
import { SessionProvider } from 'next-auth/react';
// internal
import { ChakraProvider } from '@chakra-ui/react';
import theme from './theme/theme';
import './globals.css';

export const metadata = {
  title: 'Next.js trading analytics',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <ChakraProvider theme={theme}>{children}</ChakraProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
