// default
import { Roboto } from 'next/font/google';
// external
import { SessionProvider } from 'next-auth/react';
// internal
import { ChakraProvider } from '@chakra-ui/react';
import theme from './theme/theme';
import './globals.css';

export const metadata = {
  title: 'Trading analytics',
  description: 'Generated by Next.js',
};

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} sans-serif`}>
        <SessionProvider>
          <ChakraProvider theme={theme}>{children}</ChakraProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
